image:
  file: .gitpod.Dockerfile

tasks:
  - name: Drupal start
    init: |
      lando start
      lando composer install
      gp preview $(gp url $(lando info --format=json | jq -r ".[0].urls[1]" | sed -e 's#http://localhost:\(\)#\1#'))